import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from './designTokens';

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  centerContainer: {
    flex: 1,
    backgroundColor: colors.canvas,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: colors.inkMuted,
    marginTop: 12,
    fontSize: 14,
    fontWeight: '600',
  },
  mainContent: {
    flex: 1,
  },
  loadingWaitOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  loadingWaitCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: spacing.xxl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  loadingWaitIllustration: {
    marginBottom: spacing.sm,
  },
  loadingWaitTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.ink,
    marginBottom: 6,
    textAlign: 'center',
  },
  loadingWaitSubtitle: {
    fontSize: 13,
    color: colors.primary,
    marginBottom: 12,
    textAlign: 'center',
    fontWeight: '600',
  },
  loadingWaitMessage: {
    fontSize: 12,
    color: colors.inkMuted,
    lineHeight: 18,
    textAlign: 'center',
    marginLeft: spacing.sm,
  },
  loadingWaitProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  loadingWaitNoteBox: {
    backgroundColor: colors.lavenderSoft,
    borderRadius: radius.md,
    padding: spacing.md,
    width: '100%',
    borderWidth: 1,
    borderColor: '#DED7ED',
    alignItems: 'center',
  },
  loadingWaitNoteText: {
    fontSize: 12,
    color: colors.inkMuted,
    textAlign: 'center',
    lineHeight: 18,
    fontWeight: '500',
  },
  loadingWaitCancelBtn: {
    marginTop: 16,
    backgroundColor: colors.primarySoft,
    borderWidth: 1.2,
    borderColor: colors.border,
    paddingVertical: 9,
    paddingHorizontal: 22,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  loadingWaitCancelBtnText: {
    color: colors.primaryPressed,
    fontSize: 13,
    fontWeight: 'bold',
  },
  fullModalContainer: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  fullModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#ffffff',
  },
  fullModalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.ink,
  },
  fullModalBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1.2,
    borderColor: colors.border,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 10,
  },
  fullModalBackBtnText: {
    color: colors.primaryPressed,
    fontSize: 13,
    fontWeight: 'bold',
  },
  fullModalCloseBtn: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  fullModalCloseBtnText: {
    color: colors.primaryPressed,
    fontSize: 13,
    fontWeight: 'bold',
  },
  fullModalSaveBtn: {
    backgroundColor: colors.primaryPressed,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  fullModalSaveBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 'bold',
  },
});
