import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff1f4',
  },
  centerContainer: {
    flex: 1,
    backgroundColor: '#fff1f4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#9f1239',
    marginTop: 12,
    fontSize: 14,
    fontWeight: '600',
  },
  mainContent: {
    flex: 1,
  },
  loadingWaitOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  loadingWaitCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#fecdd3',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
  },
  loadingWaitTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#881337',
    marginBottom: 6,
    textAlign: 'center',
  },
  loadingWaitSubtitle: {
    fontSize: 13,
    color: '#e11d48',
    marginBottom: 12,
    textAlign: 'center',
    fontWeight: '600',
  },
  loadingWaitMessage: {
    fontSize: 13,
    color: '#334155',
    lineHeight: 19,
    textAlign: 'center',
    marginBottom: 16,
  },
  loadingWaitNoteBox: {
    backgroundColor: '#fff1f4',
    borderRadius: 10,
    padding: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: '#fecdd3',
    alignItems: 'center',
  },
  loadingWaitNoteText: {
    fontSize: 11,
    color: '#9f1239',
    textAlign: 'center',
    lineHeight: 16,
  },
  fullModalContainer: {
    flex: 1,
    backgroundColor: '#fff1f4',
  },
  fullModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#fecdd3',
    backgroundColor: '#ffffff',
  },
  fullModalTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#881337',
  },
  fullModalCloseBtn: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fda4af',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  fullModalCloseBtnText: {
    color: '#be123c',
    fontSize: 13,
    fontWeight: 'bold',
  },
  fullModalSaveBtn: {
    backgroundColor: '#f43f5e',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  fullModalSaveBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 'bold',
  },
});
