import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fafaf9',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e7e5e4',
    backgroundColor: '#ffffff',
  },
  headerBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0f766e',
    backgroundColor: '#ccfbf1',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1c1917',
  },
  headerSub: {
    fontSize: 12,
    color: '#78716c',
    marginTop: 2,
  },
  closeBtn: {
    backgroundColor: '#f5f5f4',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d6d3d1',
  },
  closeBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#44403c',
  },
  filterSection: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f4',
    paddingBottom: 10,
  },
  chipRow: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 6,
  },
  topicChip: {
    paddingHorizontal: 13,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#f5f5f4',
    borderWidth: 1,
    borderColor: '#e7e5e4',
  },
  topicChipActive: {
    backgroundColor: '#0f766e',
    borderColor: '#0f766e',
  },
  topicChipText: {
    fontSize: 12,
    color: '#57534e',
    fontWeight: '600',
  },
  topicChipTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  utilRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 4,
  },
  utilCountText: {
    fontSize: 12,
    color: '#78716c',
    fontWeight: '600',
  },
  utilBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: '#f5f5f4',
  },
  utilBtnText: {
    fontSize: 11,
    color: '#57534e',
  },
  body: {
    flex: 1,
  },
  bodyPadding: {
    padding: 16,
    paddingBottom: 40,
  },
  questionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e7e5e4',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  qNumBadge: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0f766e',
    backgroundColor: '#f0fdfa',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
  },
  topicBadge: {
    fontSize: 11,
    color: '#78716c',
    backgroundColor: '#f5f5f4',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
  },
  unbookmarkBtn: {
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fde68a',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  unbookmarkBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#b45309',
  },
  stemText: {
    fontSize: 14.5,
    fontWeight: '700',
    color: '#1c1917',
    lineHeight: 22,
    marginBottom: 12,
  },
  optionsBox: {
    gap: 6,
    marginBottom: 12,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#fafaf9',
    borderWidth: 1,
    borderColor: '#f5f5f4',
    gap: 8,
  },
  optionRowCorrect: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  optNum: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#78716c',
    width: 18,
  },
  optNumCorrect: {
    color: '#16a34a',
  },
  optText: {
    fontSize: 13,
    color: '#292524',
    flex: 1,
  },
  optTextCorrect: {
    color: '#15803d',
    fontWeight: '700',
  },
  correctBadge: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#16a34a',
    backgroundColor: '#dcfce7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  explToggleBtn: {
    backgroundColor: '#f5f5f4',
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: 'center',
    marginBottom: 6,
  },
  explToggleBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#57534e',
  },
  explBox: {
    backgroundColor: '#fefce8',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fef08a',
    marginTop: 4,
  },
  explTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#854d0e',
    marginBottom: 4,
  },
  explBody: {
    fontSize: 12.5,
    color: '#713f12',
    lineHeight: 18,
    marginBottom: 6,
  },
  hintBox: {
    backgroundColor: '#fff1f2',
    borderRadius: 6,
    padding: 8,
    borderWidth: 1,
    borderColor: '#ffe4e6',
  },
  hintTitle: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#be123c',
    marginBottom: 2,
  },
  hintBody: {
    fontSize: 11.5,
    color: '#9f1239',
    lineHeight: 16,
  },
  emptyCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    marginTop: 30,
    borderWidth: 1,
    borderColor: '#e7e5e4',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1c1917',
    marginBottom: 6,
    textAlign: 'center',
  },
  emptyDesc: {
    fontSize: 13,
    color: '#78716c',
    lineHeight: 19,
    textAlign: 'center',
  },
});
