import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '../../styles/designTokens';

export const topicModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(64, 48, 56, 0.44)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  card: {
    width: '100%',
    maxWidth: 460,
    maxHeight: '92%',
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  cardCompact: {
    borderRadius: radius.lg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    backgroundColor: '#FFF9FB',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerCopy: {
    flex: 1,
    paddingRight: spacing.md,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.4,
    marginBottom: spacing.xs,
  },
  title: {
    color: colors.ink,
    fontSize: 21,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  guide: {
    color: colors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: spacing.xs,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
  },
  closeButtonText: {
    color: colors.primaryPressed,
    fontSize: 24,
    lineHeight: 25,
    fontWeight: '400',
  },
  scrollArea: {
    flexShrink: 1,
  },
  scrollContent: {
    padding: spacing.xl,
    paddingBottom: spacing.lg,
  },
  fieldHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  optionalText: {
    color: colors.inkMuted,
    fontSize: 11,
    marginBottom: spacing.sm,
  },
  input: {
    minHeight: 46,
    backgroundColor: '#FFFBFC',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    fontSize: 16,
    color: colors.ink,
    marginBottom: spacing.md,
  },
  sourceEmptyCard: {
    marginBottom: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sourceEmptyText: {
    color: colors.inkMuted,
    fontSize: 11,
    lineHeight: 17,
  },
  sourceList: {
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  sourceCard: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 9,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  sourceCardSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  sourceCardCopy: {
    flex: 1,
    minWidth: 0,
  },
  sourceCardTitle: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  sourceCardTitleSelected: {
    color: colors.primaryPressed,
  },
  sourceCardMeta: {
    marginTop: 3,
    color: colors.inkMuted,
    fontSize: 10,
  },
  sourceCheck: {
    width: 20,
    height: 20,
    marginLeft: spacing.sm,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceCheckSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  sourceCheckText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  categoryChip: {
    width: '47%',
    minWidth: 86,
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  categoryChipCompact: {
    width: '47%',
  },
  categoryChipSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  categoryIcon: {
    fontSize: 13,
    marginRight: 5,
  },
  categoryText: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  categoryTextSelected: {
    color: colors.primaryPressed,
    fontWeight: '800',
  },
  levelLabel: {
    marginTop: spacing.lg,
  },
  levelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  levelCard: {
    width: '47%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 58,
    paddingHorizontal: 10,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  levelCardSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  levelIcon: {
    fontSize: 16,
    marginRight: spacing.sm,
  },
  levelCopy: {
    flex: 1,
    minWidth: 0,
  },
  levelTitle: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  levelTitleSelected: {
    color: colors.primaryPressed,
  },
  levelDescription: {
    color: colors.inkMuted,
    fontSize: 9,
    marginTop: 2,
  },
  levelDescriptionSelected: {
    color: colors.primary,
  },
  radio: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#CDBFC4',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  radioSelected: {
    borderColor: colors.primary,
  },
  radioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  aiNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: spacing.lg,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.lavenderSoft,
  },
  aiNoteIcon: {
    color: colors.lavender,
    fontSize: 14,
    fontWeight: '800',
    marginRight: spacing.sm,
  },
  aiNoteText: {
    flex: 1,
    color: '#655A82',
    fontSize: 11,
    lineHeight: 17,
  },
  actions: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: '#FFFDFE',
  },
  actionButton: {
    minHeight: 46,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    width: 94,
    backgroundColor: colors.primarySoft,
  },
  cancelButtonText: {
    color: colors.primaryPressed,
    fontSize: 13,
    fontWeight: '800',
  },
  submitButton: {
    flex: 1,
    backgroundColor: colors.primaryPressed,
    ...shadows.action,
  },
  submitButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
  },
  submittingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
});

