import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '../../styles/designTokens';

export const settingsBaseStyles = StyleSheet.create({
  tabContent: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  scrollPadding: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: 48,
  },
  pageIntro: {
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.lg,
  },
  pageEyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.3,
    marginBottom: spacing.xs,
  },
  pageTitle: {
    color: colors.ink,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  pageDescription: {
    color: colors.inkMuted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: spacing.xs,
  },
  settingsGroup: {
    marginBottom: spacing.xl,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.primarySoft,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
  },
  groupIndex: {
    color: colors.primary,
    fontSize: 11,
    lineHeight: 18,
    fontWeight: '800',
    marginRight: spacing.sm,
    marginTop: 1,
  },
  groupHeaderCopy: {
    flex: 1,
  },
  groupTitle: {
    color: colors.ink,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '800',
  },
  groupDescription: {
    color: colors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 1,
  },
  manualBanner: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    ...shadows.soft,
  },
  manualBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  manualBadge: {
    minWidth: 48,
    height: 28,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lavenderSoft,
    marginRight: spacing.sm,
  },
  manualBadgeText: {
    color: colors.lavender,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  manualBannerCopy: {
    flex: 1,
  },
  manualBannerTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.ink,
  },
  manualBannerSub: {
    fontSize: 11,
    color: colors.inkMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  manualBannerButton: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginLeft: spacing.sm,
  },
  manualBannerButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.ink,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    ...shadows.soft,
  },
  cardSectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.ink,
    marginBottom: 4,
  },
  promptGuideText: {
    fontSize: 12,
    color: colors.inkMuted,
    marginBottom: 12,
    lineHeight: 17,
  },
  inputField: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.ink,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 10,
  },
  primaryActionButton: {
    backgroundColor: colors.primaryPressed,
    borderRadius: radius.md,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  connectedBadge: {
    backgroundColor: colors.mintSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: '#C9E1D9',
  },
  connectedBadgeText: {
    color: colors.mint,
    fontSize: 11,
    fontWeight: '800',
  },
  disconnectedBadge: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: '#EDC6D0',
  },
  disconnectedBadgeText: {
    color: colors.danger,
    fontSize: 11,
    fontWeight: '700',
  },
  keyInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  keyInputField: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.ink,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  saveSuccessBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  saveSuccessTitle: {
    color: '#059669',
    fontSize: 12,
    fontWeight: 'bold',
  },
  savedKeyBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  savedKeyTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#881337',
  },
  savedKeySubText: {
    fontSize: 11,
    color: colors.inkMuted,
    lineHeight: 16,
    marginTop: 2,
  },
  keyActionSmallBtn: {
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  keyActionSmallBtnText: {
    color: colors.ink,
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmActiveBadge: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EDC6D0',
  },
  alarmActiveBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primaryPressed,
  },
  alarmCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  alarmSubGuide: {
    fontSize: 11,
    color: colors.inkMuted,
    marginTop: 2,
    marginBottom: 8,
  },
  dayChipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  dayChipBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayChipBtnActive: {
    backgroundColor: colors.primaryPressed,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 2,
  },
  dayChipBtnInactive: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dayChipBtnTextActive: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  dayChipBtnTextInactive: {
    color: colors.inkMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  weekendToggleBtnSmallTextOff: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: 'bold',
  },
});

