import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../styles/designTokens';

export const settingsDetailStyles = StyleSheet.create({
  goalCard: {
    paddingHorizontal: 0,
    paddingVertical: spacing.md,
  },
  goalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  goalCardTitle: {
    marginBottom: 0,
  },
  goalInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 8,
  },
  goalInputCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1.2,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 4,
    height: 36,
    minWidth: 74,
    maxWidth: 92,
    gap: 4,
  },
  goalInputField: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.ink,
    textAlign: 'center',
    width: 26,
    padding: 0,
    margin: 0,
  },
  goalInputSuffix: {
    fontSize: 12.5,
    color: colors.primaryPressed,
    fontWeight: '700',
  },
  goalValidationText: {
    color: colors.danger,
    fontSize: 11,
    textAlign: 'center',
    marginTop: 7,
  },
  goalSaveButton: {
    minHeight: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryPressed,
    paddingHorizontal: 12,
  },
  goalSaveButtonDisabled: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  goalSaveButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
  },
  goalSaveButtonTextDisabled: {
    color: colors.inkMuted,
  },
  alarmSection: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  alarmSummaryButton: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  alarmSummaryCopy: {
    flex: 1,
  },
  alarmSummaryTitle: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '800',
  },
  alarmSummaryText: {
    color: colors.inkMuted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 1,
  },
  alarmSummaryChevron: {
    color: colors.primaryPressed,
    fontSize: 18,
    lineHeight: 20,
    fontWeight: '800',
    marginLeft: spacing.md,
  },
  alarmExpandedBody: {
    paddingBottom: spacing.md,
  },
  alarmEnabledRow: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  alarmEnabledCopy: {
    flex: 1,
    paddingRight: spacing.sm,
  },
  alarmEnabledTitle: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  alarmEnabledDescription: {
    color: colors.inkMuted,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 1,
  },
  compactDayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  alarmControlsDisabled: {
    opacity: 0.48,
  },
  alarmTimesHeader: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  alarmTimesTitle: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  alarmTimesGuide: {
    color: colors.inkMuted,
    fontSize: 9,
    lineHeight: 13,
    marginLeft: 6,
  },
  addAlarmTimeButton: {
    minHeight: 32,
    justifyContent: 'center',
    backgroundColor: colors.mintSoft,
    borderWidth: 1,
    borderColor: '#C9E1D9',
    borderRadius: 9,
    paddingHorizontal: 10,
  },
  addAlarmTimeButtonDisabled: {
    opacity: 0.45,
  },
  addAlarmTimeText: {
    color: colors.mint,
    fontSize: 11,
    fontWeight: '800',
  },
  alarmTimesScroll: {
    maxHeight: 184,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
  },
  alarmTimesEmptyContainer: {
    minHeight: 46,
    justifyContent: 'center',
  },
  alarmTimeRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
  },
  alarmTimeRowDivider: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  alarmTimeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.mint,
    marginRight: 10,
  },
  alarmTimeInput: {
    width: '100%',
    height: 25,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: colors.ink,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'left',
    letterSpacing: -0.2,
  },
  removeAlarmTimeButton: {
    width: 19,
    height: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeAlarmTimeText: {
    color: colors.inkMuted,
    fontSize: 15,
    lineHeight: 17,
    fontWeight: '500',
  },
  alarmTimeChipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  alarmMiniCard: {
    width: '31.5%',
    minHeight: 58,
    justifyContent: 'space-between',
    backgroundColor: '#FAF6F7',
    borderWidth: 1,
    borderColor: '#E8DDE0',
    borderRadius: 12,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  alarmMiniCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 17,
  },
  alarmMiniCardLabel: {
    color: colors.primary,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  addAlarmMiniCard: {
    width: '31.5%',
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mintSoft,
    borderWidth: 1,
    borderColor: '#C9E1D9',
    borderRadius: 12,
  },
  addAlarmMiniIcon: {
    color: colors.mint,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '700',
  },
  alarmTimeChip: {
    height: 34,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#E4CDD3',
    borderRadius: 10,
    paddingLeft: 4,
    paddingRight: 3,
  },
  addAlarmTimeChip: {
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mintSoft,
    borderWidth: 1,
    borderColor: '#C9E1D9',
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  emptyAlarmTimeButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyAlarmTimeText: {
    color: colors.mint,
    fontSize: 11,
    fontWeight: '800',
  },
  alarmTimeError: {
    color: colors.danger,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 5,
  },
  alarmItemBlock: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    marginBottom: 10,
  },
  alarmItemBlockDisabled: {
    backgroundColor: '#F7F6F5',
    borderColor: colors.border,
  },
  alarmItemTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  alarmItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  alarmPeriodMarker: {
    width: 28,
    color: colors.lavender,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  alarmItemTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.ink,
  },
  alarmItemSubText: {
    fontSize: 10,
    color: colors.inkMuted,
  },
  alarmToggleBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  alarmToggleOn: {
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: '#EDC6D0',
  },
  alarmToggleOff: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  alarmToggleTextOn: {
    color: colors.primaryPressed,
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmToggleTextOff: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  alarmControlRowDisabled: {
    backgroundColor: '#F7F6F5',
    borderColor: colors.border,
  },
  stepperArrowBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: '#EDC6D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperArrowBtnDisabled: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
  },
  stepperArrowText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.primaryPressed,
  },
  stepperArrowTextDisabled: {
    color: '#cbd5e1',
  },
  timeDisplayCenter: {
    alignItems: 'center',
  },
  timeDisplayText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.ink,
  },
  timeDisplaySub: {
    fontSize: 10,
    color: colors.primary,
    marginTop: 1,
    fontWeight: '600',
  },
  unifiedTimeRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  unifiedTimeTitle: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  unifiedTimeGuide: {
    color: colors.inkMuted,
    fontSize: 9,
    lineHeight: 13,
    marginTop: 1,
  },
  timeInputsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeInputGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeInput: {
    width: 44,
    height: 38,
    paddingHorizontal: 4,
    paddingVertical: 0,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DFC1C9',
    backgroundColor: colors.surface,
    color: colors.ink,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  timeInputDisabled: {
    color: '#A8ADB5',
    backgroundColor: '#F7F6F5',
    borderColor: colors.border,
  },
  timeInputLabel: {
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: '700',
    marginLeft: 3,
  },
  timeColon: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '800',
    marginHorizontal: 5,
  },
  compactCard: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    paddingHorizontal: 0,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 0,
  },
  versionFooter: {
    alignSelf: 'stretch',
    paddingTop: 5,
  },
  versionFooterRow: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  versionFooterInlineText: {
    color: colors.inkMuted,
    fontSize: 9,
    fontWeight: '600',
    marginRight: 6,
  },
  versionFooterTitle: {
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: '800',
  },
  versionFooterSubtitle: {
    color: colors.inkMuted,
    fontSize: 9,
    lineHeight: 13,
    marginTop: 1,
  },
  versionFooterButton: {
    minWidth: 34,
    minHeight: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    paddingHorizontal: 5,
  },
  versionFooterButtonText: {
    color: colors.inkMuted,
    fontSize: 8,
    fontWeight: '800',
  },
  versionFooterButtonTextActive: {
    color: colors.white,
    fontSize: 8,
    fontWeight: '800',
  },
  compactCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  compactCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.ink,
    marginBottom: 2,
  },
  compactCardSubtitle: {
    fontSize: 11,
    color: colors.inkMuted,
  },
  compactBtnGroup: {
    flexDirection: 'row',
    gap: 6,
  },
  miniBtnPrimary: {
    backgroundColor: colors.primaryPressed,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  miniBtnPrimaryText: { color: '#ffffff', fontSize: 12, fontWeight: '700' },
  miniBtnSecondary: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  miniBtnSecondaryText: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  miniResetBtn: {
    backgroundColor: '#FFF7F7',
    borderWidth: 1,
    borderColor: '#fca5a5',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  miniResetBtnText: { color: colors.danger, fontSize: 11, fontWeight: '700' },
  apiSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  apiSummaryCopy: {
    flex: 1,
    marginRight: spacing.sm,
  },
  apiTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  apiTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
    marginRight: spacing.sm,
  },
  apiProviderText: {
    color: colors.inkMuted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  apiActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  apiEditHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  apiInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  apiCancelText: {
    color: colors.inkMuted,
    fontSize: 11,
  },
  apiSaveButton: {
    paddingVertical: 11,
    paddingHorizontal: spacing.lg,
  },
  dangerActionButton: {
    backgroundColor: '#FFF7F7',
    borderColor: '#F1C8CD',
  },
  dangerActionText: {
    color: colors.danger,
  },
  resetCard: {
    backgroundColor: '#FFFCFC',
    borderColor: '#F1E1E3',
  },
  resetTitle: {
    color: colors.inkMuted,
    fontSize: 12,
  },
  disabledText: {
    color: '#A8ADB5',
  },
  updateButton: {
    backgroundColor: colors.lavender,
  },

});

