import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '../../styles/designTokens';

export const styles = StyleSheet.create({
  tabContent: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  scrollPadding: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: 48,
  },
  pageIntro: {
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.xxl,
  },
  pageEyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.3,
    marginBottom: spacing.xs,
  },
  pageTitle: {
    color: colors.ink,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  pageDescription: {
    color: colors.inkMuted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: spacing.xs,
  },
  settingsGroup: {
    marginBottom: spacing.xl,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.sm,
  },
  groupIndex: {
    color: colors.primary,
    fontSize: 11,
    lineHeight: 18,
    fontWeight: '800',
    marginRight: spacing.sm,
    marginTop: 1,
  },
  groupHeaderCopy: {
    flex: 1,
  },
  groupTitle: {
    color: colors.ink,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '800',
  },
  groupDescription: {
    color: colors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 1,
  },
  manualBanner: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    ...shadows.soft,
  },
  manualBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  manualBadge: {
    minWidth: 48,
    height: 28,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lavenderSoft,
    marginRight: spacing.sm,
  },
  manualBadgeText: {
    color: colors.lavender,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  manualBannerCopy: {
    flex: 1,
  },
  manualBannerTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.ink,
  },
  manualBannerSub: {
    fontSize: 11,
    color: colors.inkMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  manualBannerArrow: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primary,
    marginLeft: spacing.sm,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    ...shadows.soft,
  },
  cardSectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.ink,
    marginBottom: 4,
  },
  promptGuideText: {
    fontSize: 12,
    color: colors.inkMuted,
    marginBottom: 12,
    lineHeight: 17,
  },
  inputField: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.ink,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 10,
  },
  primaryActionButton: {
    backgroundColor: colors.primaryPressed,
    borderRadius: radius.md,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  connectedBadge: {
    backgroundColor: colors.mintSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: '#C9E1D9',
  },
  connectedBadgeText: {
    color: colors.mint,
    fontSize: 11,
    fontWeight: '800',
  },
  disconnectedBadge: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: '#EDC6D0',
  },
  disconnectedBadgeText: {
    color: colors.danger,
    fontSize: 11,
    fontWeight: '700',
  },
  keyInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  keyInputField: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.ink,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  saveSuccessBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  saveSuccessTitle: {
    color: '#059669',
    fontSize: 12,
    fontWeight: 'bold',
  },
  savedKeyBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  savedKeyTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#881337',
  },
  savedKeySubText: {
    fontSize: 11,
    color: colors.inkMuted,
    lineHeight: 16,
    marginTop: 2,
  },
  keyActionSmallBtn: {
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  keyActionSmallBtnText: {
    color: colors.ink,
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmActiveBadge: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EDC6D0',
  },
  alarmActiveBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primaryPressed,
  },
  alarmCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  alarmSubGuide: {
    fontSize: 11,
    color: colors.inkMuted,
    marginTop: 2,
    marginBottom: 8,
  },
  dayChipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  dayChipBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayChipBtnActive: {
    backgroundColor: colors.primaryPressed,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 2,
  },
  dayChipBtnInactive: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dayChipBtnTextActive: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  dayChipBtnTextInactive: {
    color: colors.inkMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  weekendToggleBtnSmallTextOff: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: 'bold',
  },
  goalInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 6,
    marginBottom: 12,
  },
  goalInputCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1.2,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 4,
    height: 42,
    minWidth: 95,
    maxWidth: 130,
    gap: 4,
  },
  goalInputField: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.ink,
    textAlign: 'center',
    width: 32,
    padding: 0,
    margin: 0,
  },
  goalInputSuffix: {
    fontSize: 12.5,
    color: colors.primaryPressed,
    fontWeight: '700',
  },
  goalPresetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  goalPresetChip: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalPresetChipActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  goalPresetText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.inkMuted,
  },
  goalPresetTextActive: {
    color: colors.primaryPressed,
    fontWeight: 'bold',
  },
  alarmItemBlock: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    marginBottom: 10,
  },
  alarmItemBlockDisabled: {
    backgroundColor: '#F7F6F5',
    borderColor: colors.border,
  },
  alarmItemTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  alarmItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  alarmPeriodMarker: {
    width: 28,
    color: colors.lavender,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  alarmItemTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.ink,
  },
  alarmItemSubText: {
    fontSize: 10,
    color: colors.inkMuted,
  },
  alarmToggleBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  alarmToggleOn: {
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: '#EDC6D0',
  },
  alarmToggleOff: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  alarmToggleTextOn: {
    color: colors.primaryPressed,
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmToggleTextOff: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  alarmControlRowDisabled: {
    backgroundColor: '#F7F6F5',
    borderColor: colors.border,
  },
  stepperArrowBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: '#EDC6D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperArrowBtnDisabled: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
  },
  stepperArrowText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.primaryPressed,
  },
  stepperArrowTextDisabled: {
    color: '#cbd5e1',
  },
  timeDisplayCenter: {
    alignItems: 'center',
  },
  timeDisplayText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.ink,
  },
  timeDisplaySub: {
    fontSize: 10,
    color: colors.primary,
    marginTop: 1,
    fontWeight: '600',
  },
  compactCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    ...shadows.soft,
  },
  compactCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  compactCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.ink,
    marginBottom: 2,
  },
  compactCardSubtitle: {
    fontSize: 11,
    color: colors.inkMuted,
  },
  compactBtnGroup: {
    flexDirection: 'row',
    gap: 6,
  },
  miniBtnPrimary: {
    backgroundColor: colors.primaryPressed,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  miniBtnPrimaryText: { color: '#ffffff', fontSize: 12, fontWeight: '700' },
  miniBtnSecondary: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  miniBtnSecondaryText: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  miniResetBtn: {
    backgroundColor: '#FFF7F7',
    borderWidth: 1,
    borderColor: '#fca5a5',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  miniResetBtnText: { color: colors.danger, fontSize: 11, fontWeight: '700' },
  apiSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  apiSummaryCopy: {
    flex: 1,
    marginRight: spacing.sm,
  },
  apiTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  apiTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
    marginRight: spacing.sm,
  },
  apiProviderText: {
    color: colors.inkMuted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  apiActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  apiEditHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  apiInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  apiCancelText: {
    color: colors.inkMuted,
    fontSize: 11,
  },
  apiSaveButton: {
    paddingVertical: 11,
    paddingHorizontal: spacing.lg,
  },
  dangerActionButton: {
    backgroundColor: '#FFF7F7',
    borderColor: '#F1C8CD',
  },
  dangerActionText: {
    color: colors.danger,
  },
  resetCard: {
    backgroundColor: '#FFFCFC',
    borderColor: '#F1E1E3',
  },
  resetTitle: {
    color: colors.inkMuted,
    fontSize: 12,
  },
  disabledText: {
    color: '#A8ADB5',
  },
  updateButton: {
    backgroundColor: colors.lavender,
  },
});


