import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  tabContent: {
    flex: 1,
    backgroundColor: '#fff1f4',
  },
  scrollPadding: {
    padding: 16,
    paddingBottom: 40,
  },
  manualBanner: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1.5,
    borderColor: '#fda4af',
    marginBottom: 14,
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  manualBannerTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#881337',
  },
  manualBannerSub: {
    fontSize: 11,
    color: '#9f1239',
    marginTop: 2,
  },
  manualBannerArrow: {
    fontSize: 12,
    fontWeight: '700',
    color: '#e11d48',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#fecdd3',
    marginBottom: 14,
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardSectionTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#881337',
    marginBottom: 4,
  },
  promptGuideText: {
    fontSize: 12,
    color: '#64748b',
    marginBottom: 12,
    lineHeight: 17,
  },
  inputField: {
    backgroundColor: '#fff5f7',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#1f2937',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#fecdd3',
    marginBottom: 10,
  },
  primaryActionButton: {
    backgroundColor: '#f43f5e',
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  connectedBadge: {
    backgroundColor: '#ecfdf5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  connectedBadgeText: {
    color: '#059669',
    fontSize: 11,
    fontWeight: '800',
  },
  disconnectedBadge: {
    backgroundColor: '#ffe4e6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  disconnectedBadgeText: {
    color: '#be123c',
    fontSize: 11,
    fontWeight: '700',
  },
  keyInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  keyInputField: {
    flex: 1,
    backgroundColor: '#fff5f7',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#1f2937',
    fontSize: 13,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  saveSuccessBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  saveSuccessTitle: {
    color: '#059669',
    fontSize: 12,
    fontWeight: 'bold',
  },
  savedKeyBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff5f7',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  savedKeyTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#881337',
  },
  savedKeySubText: {
    fontSize: 11,
    color: '#64748b',
    lineHeight: 16,
    marginTop: 2,
  },
  keyActionSmallBtn: {
    backgroundColor: '#ffe4e6',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  keyActionSmallBtnText: {
    color: '#be123c',
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmActiveBadge: {
    backgroundColor: '#ffe4e6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  alarmActiveBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#be123c',
  },
  alarmCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  alarmSubGuide: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 2,
    marginBottom: 8,
  },
  dayChipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff5f7',
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffe4e6',
    marginBottom: 12,
  },
  dayChipBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayChipBtnActive: {
    backgroundColor: '#f43f5e',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 2,
  },
  dayChipBtnInactive: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  dayChipBtnTextActive: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  dayChipBtnTextInactive: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '600',
  },
  weekendToggleBtnSmallTextOff: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: 'bold',
  },
  goalInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 6,
    marginBottom: 12,
  },
  goalInputCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff5f7',
    borderWidth: 1,
    borderColor: '#fecdd3',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 6,
    gap: 6,
  },
  goalInputField: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#881337',
    textAlign: 'center',
    minWidth: 40,
    padding: 0,
  },
  goalInputSuffix: {
    fontSize: 13,
    color: '#be123c',
    fontWeight: '700',
  },
  goalPresetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  goalPresetChip: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalPresetChipActive: {
    backgroundColor: '#ffe4e6',
    borderColor: '#f43f5e',
  },
  goalPresetText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },
  goalPresetTextActive: {
    color: '#be123c',
    fontWeight: 'bold',
  },
  alarmItemBlock: {
    backgroundColor: '#fffafb',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fecdd3',
    padding: 12,
    marginBottom: 10,
  },
  alarmItemBlockDisabled: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
  },
  alarmItemTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  alarmItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  alarmItemTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#881337',
  },
  alarmItemSubText: {
    fontSize: 10,
    color: '#94a3b8',
  },
  alarmToggleBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  alarmToggleOn: {
    backgroundColor: '#ffe4e6',
    borderWidth: 1,
    borderColor: '#fda4af',
  },
  alarmToggleOff: {
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  alarmToggleTextOn: {
    color: '#e11d48',
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmToggleTextOff: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: 'bold',
  },
  alarmControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  alarmControlRowDisabled: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
  },
  stepperArrowBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fda4af',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperArrowBtnDisabled: {
    backgroundColor: '#f1f5f9',
    borderColor: '#e2e8f0',
  },
  stepperArrowText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#be123c',
  },
  stepperArrowTextDisabled: {
    color: '#cbd5e1',
  },
  timeDisplayCenter: {
    alignItems: 'center',
  },
  timeDisplayText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#881337',
  },
  timeDisplaySub: {
    fontSize: 10,
    color: '#e11d48',
    marginTop: 1,
    fontWeight: '600',
  },
  compactCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#fecdd3',
    marginBottom: 12,
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  compactCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  compactCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#881337',
    marginBottom: 2,
  },
  compactCardSubtitle: {
    fontSize: 11,
    color: '#64748b',
  },
  compactBtnGroup: {
    flexDirection: 'row',
    gap: 6,
  },
  miniBtnPrimary: {
    backgroundColor: '#f43f5e',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  miniBtnPrimaryText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  miniBtnSecondary: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fda4af',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  miniBtnSecondaryText: {
    color: '#be123c',
    fontSize: 12,
    fontWeight: '700',
  },
  miniResetBtn: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fca5a5',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  miniResetBtnText: {
    color: '#ef4444',
    fontSize: 11,
    fontWeight: '600',
  },
});
