import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  examContainer: {
    flex: 1,
    backgroundColor: '#fff1f4',
  },
  examHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#fecdd3',
    backgroundColor: '#ffffff',
  },
  backButton: {
    padding: 6,
  },
  backButtonText: {
    color: '#be123c',
    fontSize: 13,
    fontWeight: 'bold',
  },
  examProgressText: {
    color: '#881337',
    fontSize: 15,
    fontWeight: 'bold',
  },
  hintHeaderBtn: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fda4af',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  hintHeaderBtnText: {
    color: '#e11d48',
    fontSize: 12,
    fontWeight: 'bold',
  },
  examBody: {
    flex: 1,
    backgroundColor: '#fff1f4',
  },
  examContentContainer: {
    padding: 18,
  },
  reportContentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  quickNavRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    justifyContent: 'center',
  },
  quickNavDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#fecdd3',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  quickNavDotAnswered: {
    backgroundColor: '#fff1f2',
    borderColor: '#fda4af',
  },
  quickNavDotCurrent: {
    borderColor: '#f43f5e',
    borderWidth: 2,
    backgroundColor: '#ffe4e6',
  },
  quickNavDotText: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '700',
  },
  quickNavDotTextAnswered: {
    color: '#e11d48',
  },
  quickNavDotTextCurrent: {
    color: '#881337',
    fontWeight: '900',
  },
  questionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: '#fecdd3',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  questionIndexLabel: {
    color: '#f43f5e',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 8,
  },
  questionStem: {
    color: '#1f2937',
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '700',
  },
  optionsList: {
    gap: 12,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#fecdd3',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  optionButtonSelected: {
    borderColor: '#f43f5e',
    backgroundColor: '#fff1f2',
    borderWidth: 2,
  },
  optionIndexBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff5f7',
    borderWidth: 1,
    borderColor: '#fecdd3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  optionIndexBadgeSelected: {
    backgroundColor: '#f43f5e',
    borderColor: '#e11d48',
  },
  optionIndexText: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: 'bold',
  },
  optionIndexTextSelected: {
    color: '#ffffff',
  },
  optionText: {
    flex: 1,
    fontSize: 14,
    color: '#334155',
    lineHeight: 21,
    fontWeight: '500',
  },
  optionTextSelected: {
    color: '#881337',
    fontWeight: '700',
  },
  checkMark: {
    color: '#f43f5e',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  examFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#fecdd3',
    backgroundColor: '#ffffff',
  },
  navBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#fff1f2',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fda4af',
  },
  navBtnDisabled: {
    opacity: 0.35,
  },
  navBtnText: {
    color: '#be123c',
    fontSize: 14,
    fontWeight: 'bold',
  },
  navBtnTextDisabled: {
    color: '#94a3b8',
  },
  navBtnNext: {
    backgroundColor: '#f43f5e',
    borderColor: '#e11d48',
  },
  navBtnNextText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  submitBtn: {
    backgroundColor: '#f43f5e',
    borderColor: '#e11d48',
  },
  submitBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  reportScoreCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: '#fecdd3',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  reportScoreHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  reportScoreTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#881337',
    marginBottom: 4,
  },
  reportScoreSub: {
    fontSize: 14,
    color: '#475569',
  },
  reportGuide: {
    fontSize: 12,
    color: '#64748b',
    lineHeight: 18,
    borderTopWidth: 1,
    borderTopColor: '#fecdd3',
    paddingTop: 10,
  },
  reviewItemCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#fecdd3',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  reviewItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  reviewItemNumber: {
    fontSize: 14,
    fontWeight: '800',
    color: '#881337',
  },
  resultBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  resultBadgeCorrect: {
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  resultBadgeWrong: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  resultBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  resultBadgeTextCorrect: {
    color: '#059669',
  },
  resultBadgeTextWrong: {
    color: '#be123c',
  },
  reviewStem: {
    fontSize: 15,
    color: '#1f2937',
    fontWeight: '600',
    lineHeight: 23,
    marginBottom: 14,
  },
  reviewOptionsList: {
    gap: 8,
    marginBottom: 14,
  },
  reviewOptionRow: {
    backgroundColor: '#fff5f7',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  reviewOptionRowCorrect: {
    backgroundColor: '#ecfdf5',
    borderColor: '#10b981',
  },
  reviewOptionRowWrong: {
    backgroundColor: '#fff1f2',
    borderColor: '#f43f5e',
  },
  reviewOptionTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewOptionIndex: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#64748b',
    marginRight: 6,
  },
  reviewOptionText: {
    flex: 1,
    fontSize: 13,
    color: '#334155',
    lineHeight: 19,
  },
  reviewOptionTextCorrect: {
    color: '#065f46',
    fontWeight: 'bold',
  },
  correctTag: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
    marginLeft: 6,
  },
  myChoiceTag: {
    fontSize: 11,
    fontWeight: '800',
    color: '#be123c',
    marginLeft: 6,
  },
  distractorRationaleText: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 4,
    paddingLeft: 16,
  },
  wrongAnalysisBox: {
    backgroundColor: '#fff1f2',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  wrongAnalysisTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#be123c',
    marginBottom: 4,
  },
  wrongAnalysisText: {
    fontSize: 12,
    color: '#881337',
    lineHeight: 18,
  },
  conceptBox: {
    backgroundColor: '#fff1f4',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  conceptBoxTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#be123c',
    marginBottom: 4,
  },
  conceptBoxText: {
    fontSize: 13,
    color: '#881337',
    lineHeight: 19,
  },
  hintBox: {
    backgroundColor: '#fff8f6',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#fed7aa',
  },
  hintBoxTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#c2410c',
    marginBottom: 4,
  },
  hintBoxText: {
    fontSize: 13,
    color: '#7c2d12',
    lineHeight: 19,
  },
  explanationBox: {
    backgroundColor: '#fff5f7',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  explanationTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#881337',
    marginBottom: 4,
  },
  explanationText: {
    fontSize: 13,
    color: '#1f2937',
    lineHeight: 20,
  },
  finishReviewBtn: {
    backgroundColor: '#f43f5e',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  finishReviewBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  hintModalCard: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 22,
    borderWidth: 1.5,
    borderColor: '#fecdd3',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  hintModalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#881337',
  },
  hintModalContent: {
    fontSize: 13,
    color: '#334155',
    lineHeight: 20,
    marginBottom: 18,
  },
  closeHintBtn: {
    backgroundColor: '#f43f5e',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  closeHintBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 'bold',
  },
});
