import { StyleSheet } from 'react-native';
import { colors, radius } from '../../styles/designTokens';

export const styles = StyleSheet.create({
  examContainer: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  examHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#ffffff',
  },
  backButton: {
    padding: 6,
  },
  backButtonText: {
    color: colors.primaryPressed,
    fontSize: 13,
    fontWeight: 'bold',
  },
  examProgressText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: 'bold',
  },
  hintHeaderBtn: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  hintHeaderBtnText: {
    color: colors.primaryPressed,
    fontSize: 12,
    fontWeight: 'bold',
  },
  examBody: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  examContentContainer: {
    padding: 18,
  },
  reportContentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  quickNavRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    justifyContent: 'center',
  },
  quickNavDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  quickNavDotAnswered: {
    backgroundColor: colors.primarySoft,
    borderColor: '#DFC2CB',
  },
  quickNavDotCurrent: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: colors.primarySoft,
  },
  quickNavDotText: {
    fontSize: 13,
    color: colors.inkMuted,
    fontWeight: '700',
  },
  quickNavDotTextAnswered: {
    color: colors.primaryPressed,
  },
  quickNavDotTextCurrent: {
    color: colors.primaryPressed,
    fontWeight: '900',
  },
  questionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  questionIndexLabel: {
    color: colors.primaryPressed,
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 8,
  },
  questionStem: {
    color: colors.ink,
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '700',
  },
  optionsList: {
    gap: 12,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  optionButtonSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
    borderWidth: 2,
  },
  optionIndexBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  optionIndexBadgeSelected: {
    backgroundColor: colors.primaryPressed,
    borderColor: colors.primaryPressed,
  },
  optionIndexText: {
    color: colors.inkMuted,
    fontSize: 13,
    fontWeight: 'bold',
  },
  optionIndexTextSelected: {
    color: '#ffffff',
  },
  optionText: {
    flex: 1,
    fontSize: 14,
    color: colors.ink,
    lineHeight: 21,
    fontWeight: '500',
  },
  optionTextSelected: {
    color: colors.ink,
    fontWeight: '700',
  },
  checkMark: {
    color: colors.primaryPressed,
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  examFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: '#ffffff',
  },
  navBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  navBtnDisabled: {
    opacity: 0.35,
  },
  navBtnText: {
    color: colors.primaryPressed,
    fontSize: 14,
    fontWeight: 'bold',
  },
  navBtnTextDisabled: {
    color: '#94a3b8',
  },
  navBtnNext: {
    backgroundColor: colors.primaryPressed,
    borderColor: colors.primaryPressed,
  },
  navBtnNextText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  submitBtn: {
    backgroundColor: colors.primaryPressed,
    borderColor: colors.primaryPressed,
  },
  submitBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  reportScoreCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  reportScoreHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  reportScoreTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: colors.ink,
    marginBottom: 4,
  },
  reportScoreSub: {
    fontSize: 14,
    color: colors.inkMuted,
  },
  reportGuide: {
    fontSize: 12,
    color: colors.inkMuted,
    lineHeight: 18,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  reviewItemCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  reviewItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  reviewItemNumber: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.ink,
  },
  resultBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  resultBadgeCorrect: {
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  resultBadgeWrong: {
    backgroundColor: '#FAECEE',
    borderWidth: 1,
    borderColor: '#E6C7CD',
  },
  resultBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  resultBadgeTextCorrect: {
    color: '#059669',
  },
  resultBadgeTextWrong: {
    color: colors.danger,
  },
  reviewStem: {
    fontSize: 15,
    color: colors.ink,
    fontWeight: '600',
    lineHeight: 23,
    marginBottom: 14,
  },
  reviewOptionsList: {
    gap: 8,
    marginBottom: 14,
  },
  reviewOptionRow: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reviewOptionRowCorrect: {
    backgroundColor: '#ecfdf5',
    borderColor: '#10b981',
  },
  reviewOptionRowWrong: {
    backgroundColor: '#FAECEE',
    borderColor: '#E6C7CD',
  },
  reviewOptionTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewOptionIndex: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.inkMuted,
    marginRight: 6,
  },
  reviewOptionText: {
    flex: 1,
    fontSize: 13,
    color: colors.ink,
    lineHeight: 19,
  },
  reviewOptionTextCorrect: {
    color: '#065f46',
    fontWeight: 'bold',
  },
  correctTag: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
    marginLeft: 6,
  },
  myChoiceTag: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.danger,
    marginLeft: 6,
  },
  distractorRationaleText: {
    fontSize: 11,
    color: colors.inkMuted,
    marginTop: 4,
    paddingLeft: 16,
  },
  wrongAnalysisBox: {
    backgroundColor: '#FAECEE',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E6C7CD',
  },
  wrongAnalysisTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.danger,
    marginBottom: 4,
  },
  wrongAnalysisText: {
    fontSize: 12,
    color: colors.ink,
    lineHeight: 18,
  },
  conceptBox: {
    backgroundColor: colors.lavenderSoft,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#DED7ED',
  },
  conceptBoxTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.lavender,
    marginBottom: 4,
  },
  conceptBoxText: {
    fontSize: 13,
    color: colors.ink,
    lineHeight: 19,
  },
  hintBox: {
    backgroundColor: '#fff8f6',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#fed7aa',
  },
  hintBoxTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#c2410c',
    marginBottom: 4,
  },
  hintBoxText: {
    fontSize: 13,
    color: '#7c2d12',
    lineHeight: 19,
  },
  explanationBox: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  explanationTitle: { fontSize: 12, fontWeight: '800', color: colors.ink, marginBottom: 4 },
  explanationText: { fontSize: 13, color: colors.ink, lineHeight: 20 },
  reinforceConceptBtn: {
    backgroundColor: colors.lavenderSoft,
    borderWidth: 1,
    borderColor: '#DED7ED',
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  reinforceConceptBtnTitle: {
    color: colors.lavender,
    fontSize: 14,
    fontWeight: '800',
  },
  reinforceConceptBtnText: {
    color: colors.inkMuted,
    fontSize: 11,
    marginTop: 3,
  },
  finishReviewBtn: {
    backgroundColor: colors.primaryPressed,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  finishReviewBtnText: { color: '#ffffff', fontSize: 14, fontWeight: 'bold' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(64, 48, 56, 0.44)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  hintModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 22,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  hintModalTitle: { fontSize: 16, fontWeight: '800', color: colors.ink },
  hintModalContent: {
    fontSize: 14,
    color: colors.ink,
    lineHeight: 22,
    letterSpacing: -0.2,
  },
  closeHintBtn: {
    backgroundColor: colors.primaryPressed,
    paddingVertical: 13,
    borderRadius: 10,
    alignItems: 'center',
  },
  closeHintBtnText: { color: '#ffffff', fontSize: 14, fontWeight: 'bold' },
});
