import { StyleSheet } from 'react-native';
import { colors } from '../../styles/designTokens';

export const examReviewStyles = StyleSheet.create({
  reviewItemCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  reviewItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  reviewItemNumber: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.ink,
  },
  resultBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  resultBadgeCorrect: {
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  resultBadgeWrong: {
    backgroundColor: '#FAECEE',
    borderWidth: 1,
    borderColor: '#E6C7CD',
  },
  resultBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  resultBadgeTextCorrect: {
    color: '#059669',
  },
  resultBadgeTextWrong: {
    color: colors.danger,
  },
  reviewStem: {
    fontSize: 15,
    color: colors.ink,
    fontWeight: '600',
    lineHeight: 23,
    marginBottom: 14,
  },
  reviewOptionsList: {
    gap: 8,
    marginBottom: 14,
  },
  reviewOptionRow: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reviewOptionRowCorrect: {
    backgroundColor: '#ecfdf5',
    borderColor: '#10b981',
  },
  reviewOptionRowWrong: {
    backgroundColor: '#FAECEE',
    borderColor: '#E6C7CD',
  },
  reviewOptionTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewOptionIndex: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.inkMuted,
    marginRight: 6,
  },
  reviewOptionText: {
    flex: 1,
    fontSize: 13,
    color: colors.ink,
    lineHeight: 19,
  },
  reviewOptionTextCorrect: {
    color: '#065f46',
    fontWeight: 'bold',
  },
  correctTag: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
    marginLeft: 6,
  },
  myChoiceTag: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.danger,
    marginLeft: 6,
  },
  distractorRationaleText: {
    fontSize: 11,
    color: colors.inkMuted,
    marginTop: 4,
    paddingLeft: 16,
  },
  wrongAnalysisBox: {
    backgroundColor: '#FAECEE',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E6C7CD',
  },
  wrongAnalysisTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.danger,
    marginBottom: 4,
  },
  wrongAnalysisText: {
    fontSize: 12,
    color: colors.ink,
    lineHeight: 18,
  },
  conceptBox: {
    backgroundColor: colors.lavenderSoft,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#DED7ED',
  },
  conceptBoxTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.lavender,
    marginBottom: 4,
  },
  conceptBoxText: {
    fontSize: 13,
    color: colors.ink,
    lineHeight: 19,
  },
  hintBox: {
    backgroundColor: '#fff8f6',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#fed7aa',
  },
  hintBoxTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#c2410c',
    marginBottom: 4,
  },
  hintBoxText: {
    fontSize: 13,
    color: '#7c2d12',
    lineHeight: 19,
  },
  explanationBox: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  explanationTitle: { fontSize: 12, fontWeight: '800', color: colors.ink, marginBottom: 4 },
  explanationText: { fontSize: 13, color: colors.ink, lineHeight: 20 },
  reinforceConceptBtn: {
    backgroundColor: colors.lavenderSoft,
    borderWidth: 1,
    borderColor: '#DED7ED',
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  reinforceConceptBtnTitle: {
    color: colors.lavender,
    fontSize: 14,
    fontWeight: '800',
  },
  reinforceConceptBtnText: {
    color: colors.inkMuted,
    fontSize: 11,
    marginTop: 3,
  },
  finishReviewBtn: {
    backgroundColor: colors.primaryPressed,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  finishReviewBtnText: { color: '#ffffff', fontSize: 14, fontWeight: 'bold' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(64, 48, 56, 0.44)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  hintModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 22,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  hintModalTitle: { fontSize: 16, fontWeight: '800', color: colors.ink },
  hintModalContent: {
    fontSize: 14,
    color: colors.ink,
    lineHeight: 22,
    letterSpacing: -0.2,
  },
  closeHintBtn: {
    backgroundColor: colors.primaryPressed,
    paddingVertical: 13,
    borderRadius: 10,
    alignItems: 'center',
  },
  closeHintBtnText: { color: '#ffffff', fontSize: 14, fontWeight: 'bold' },
  hintEmptyText: {
    fontSize: 13,
    color: colors.inkMuted,
    lineHeight: 20,
    marginBottom: 12,
  },
  generateHintBtn: {
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: colors.primaryPressed,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 8,
  },
  generateHintBtnText: { color: colors.primaryPressed, fontSize: 14, fontWeight: 'bold' },
  hintLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  hintErrorText: {
    fontSize: 12,
    color: '#dc2626',
    lineHeight: 18,
  },

});

