import { Platform, StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '../../styles/designTokens';

const examReadingFont = Platform.select({
  web: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans KR", "Malgun Gothic", sans-serif',
  ios: 'System',
  android: 'sans-serif',
});

export const examActiveStyles = StyleSheet.create({
  examContainer: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  examHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#ffffff',
  },
  backButton: {
    padding: 6,
  },
  backButtonText: {
    color: colors.primaryPressed,
    fontSize: 13,
    fontWeight: 'bold',
  },
  examProgressText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: 'bold',
  },
  hintHeaderBtn: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  hintHeaderBtnText: {
    color: colors.primaryPressed,
    fontSize: 12,
    fontWeight: 'bold',
  },
  examBody: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  examContentContainer: {
    padding: 18,
  },
  reportContentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  quickNavRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    justifyContent: 'center',
  },
  quickNavDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  quickNavDotAnswered: {
    backgroundColor: colors.primarySoft,
    borderColor: '#DFC2CB',
  },
  quickNavDotCurrent: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: colors.primarySoft,
  },
  quickNavDotText: {
    fontSize: 13,
    color: colors.inkMuted,
    fontWeight: '700',
  },
  quickNavDotTextAnswered: {
    color: colors.primaryPressed,
  },
  quickNavDotTextCurrent: {
    color: colors.primaryPressed,
    fontWeight: '900',
  },
  questionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  questionIndexLabel: {
    color: colors.primaryPressed,
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 8,
  },
  questionStem: {
    color: colors.ink,
    fontFamily: examReadingFont,
    fontSize: 17,
    lineHeight: 27,
    fontWeight: '600',
  },
  optionsList: {
    gap: 12,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  optionButtonSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
    borderWidth: 2,
  },
  optionIndexBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  optionIndexBadgeSelected: {
    backgroundColor: colors.primaryPressed,
    borderColor: colors.primaryPressed,
  },
  optionIndexText: {
    color: colors.inkMuted,
    fontSize: 13,
    fontWeight: 'bold',
  },
  optionIndexTextSelected: {
    color: '#ffffff',
  },
  optionText: {
    flex: 1,
    fontFamily: examReadingFont,
    fontSize: 14,
    color: colors.ink,
    lineHeight: 21,
    fontWeight: '500',
  },
  optionTextSelected: {
    color: colors.ink,
    fontWeight: '600',
  },
  answerInputText: {
    fontFamily: examReadingFont,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
  },
  checkMark: {
    color: colors.primaryPressed,
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  examFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: '#ffffff',
  },
  navBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  navBtnDisabled: {
    opacity: 0.35,
  },
  navBtnText: {
    color: colors.primaryPressed,
    fontSize: 14,
    fontWeight: 'bold',
  },
  navBtnTextDisabled: {
    color: '#94a3b8',
  },
  navBtnNext: {
    backgroundColor: colors.primaryPressed,
    borderColor: colors.primaryPressed,
  },
  navBtnNextText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  submitBtn: {
    backgroundColor: colors.primaryPressed,
    borderColor: colors.primaryPressed,
  },
  submitBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  reportScoreCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  reportScoreHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  reportScoreTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: colors.ink,
    marginBottom: 4,
  },
  reportScoreSub: {
    fontSize: 14,
    color: colors.inkMuted,
  },
  reportGuide: {
    fontSize: 12,
    color: colors.inkMuted,
    lineHeight: 18,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
});

